### ISSUE TITLE
Copy editing

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/camjam-kit-1#1]
@lauraclay @LornaLynch could one of you please copy edit the worksheet and template files?

Thanks

**Comment by LornaLynch** [comment]
Noting that the link to the cover image in README is broken, but this will presumably be fixed when the cover image is uploaded.

**Comment by LornaLynch** [comment]
Minor semantic quibble, @bennuttall: in line 176, is it just 'blink' which controls all the lights together, or do 'on', 'off', and 'blink' all do it? I want to make sure the verb agreement is correct :) 

Other than this and the broken image link (above), I think we're fine.

**Comment by bennuttall** [comment]
I just reread and see the ambiguity! `on`, `off` and `blink` all control all the lights together.

Thanks both!

**Comment by LornaLynch** [comment]
Yay! Thanks. All good now.
