### ISSUE TITLE
RPi V1 incompatability

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/camjam-kit-1#4]
Great work Ben. Given the small number of GPIO ports required for this exercise, would it be possible to amend to be compatible with the 26 pin connector on a V1?

I'm happy to create a PR for this if it would get accepted/merged (text plus diagrams)

**Comment by bennuttall** [comment]
I'd rather not, as the wiring is much neater this way. It's easy enough to choose different pins to use.

Sorry/thanks!
